"""initial schema: pipeline_runs, documents, flags, confidence_scores

Revision ID: 444439395ac0
Revises: 
Create Date: 2026-07-21 00:23:36.785827

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '444439395ac0'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schema_id', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('worker_history', sa.JSON(), nullable=False),
    sa.Column('correction_history', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_content_hash'), 'pipeline_runs', ['content_hash'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_schema_id'), 'pipeline_runs', ['schema_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_started_at'), 'pipeline_runs', ['started_at'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('schema_id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('natural_id', sa.String(), nullable=True),
    sa.Column('party_name', sa.String(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_document_date'), 'documents', ['document_date'], unique=False)
    op.create_index(op.f('ix_documents_natural_id'), 'documents', ['natural_id'], unique=False)
    op.create_index(op.f('ix_documents_party_name'), 'documents', ['party_name'], unique=False)
    op.create_index(op.f('ix_documents_run_id'), 'documents', ['run_id'], unique=False)
    op.create_index(op.f('ix_documents_schema_id'), 'documents', ['schema_id'], unique=False)
    op.create_index('ix_documents_schema_natural_id', 'documents', ['schema_id', 'natural_id'], unique=False)
    op.create_table('confidence_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confidence_scores_document_id'), 'confidence_scores', ['document_id'], unique=False)
    op.create_table('flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('layer', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flags_document_id'), 'flags', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flags_document_id'), table_name='flags')
    op.drop_table('flags')
    op.drop_index(op.f('ix_confidence_scores_document_id'), table_name='confidence_scores')
    op.drop_table('confidence_scores')
    op.drop_index('ix_documents_schema_natural_id', table_name='documents')
    op.drop_index(op.f('ix_documents_schema_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_run_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_party_name'), table_name='documents')
    op.drop_index(op.f('ix_documents_natural_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_date'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_pipeline_runs_started_at'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_schema_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_content_hash'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
